on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4      # THIS WAS MISSING
        
        - name: Set env
          run: echo "AWS_ACCESS_KEY_ID=$(echo $AWS_ACCESS_KEY_ID | cut -c 1-6)" >> $AWS_ACCESS_KEY_ID
        
        - name: Set env2
          run: echo "AWS_SECRET_ACCESS_KEY=$(echo $AWS_SECRET_ACCESS_KEY | cut -c 1-6)" >> $AWS_SECRET_ACCESS_KEY
        
        - name: Set env3
          run: echo "us-east-1" >> $AWS_REGION
        
        - uses: opentofu/setup-opentofu@v1.0.4
        
        - name: OpenTofu Init
          run: tofu init
            
        - name: OpenTofu Plan
          id: plan
          run: tofu plan -no-color
            
        - name: Echo Plan Output
          run: |
            echo "${{ steps.plan.outputs.stdout }}"
            echo "${{ steps.plan.outputs.stderr }}"
            echo "${{ steps.plan.outputs.exitcode }}"