on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    run:
        runs-on: ubuntu-latest
        environment: dev
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4      # THIS WAS MISSING
        
        - uses: opentofu/setup-opentofu@v1.0.4
        
        - name: OpenTofu Init
          run: tofu init
            
        - name: OpenTofu Plan
          id: plan
          env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION: "us-east-2"
          run: tofu plan -no-color
            
        - name: Echo Plan Output
          run: |
            echo "${{ steps.plan.outputs.stdout }}"
            echo "${{ steps.plan.outputs.stderr }}"
            echo "${{ steps.plan.outputs.exitcode }}"